apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: vvanio/rotten-potatoes:v1
          ports: 
            - containerPort: 5000
          env: 
            - name: MONGO_DB
             value: admin 
            - name: MONGO_HOST
             value: mongo-service 
            - name: MONGO_PORT
             value: "27017" 
            - name: MONGO_USERNAME
             value: mongouser 
            - name: MONGO_PASSWORD
             value: mongopwd 